# Generated by Django 4.1.1 on 2022-11-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=1000, verbose_name='List Of Charges')),
            ],
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, verbose_name='Defendant Name')),
                ('age', models.IntegerField(verbose_name='Defendant Age')),
                ('gender', models.CharField(max_length=1, verbose_name='Defendant Gender')),
                ('email', models.EmailField(blank=True, max_length=260, verbose_name='Defendant Email Address')),
                ('totalConvictions', models.IntegerField(verbose_name='Total Number Of Convictions Defendant Has Had')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, verbose_name='Judge Name')),
                ('age', models.IntegerField(verbose_name='Judge Age')),
                ('gender', models.CharField(max_length=1, verbose_name='Judge Gender')),
                ('email', models.EmailField(blank=True, max_length=260, verbose_name='Judge Email Address')),
                ('totalCases', models.IntegerField(verbose_name='Total Number Of Cases Judge Has Presided Over')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Defendant Group Name')),
                ('members', models.ManyToManyField(to='cases.judge')),
            ],
        ),
        migrations.CreateModel(
            name='DefendantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Defendant Group Name')),
                ('members', models.ManyToManyField(to='cases.defendant')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury', models.CharField(blank=True, default='F', max_length=1)),
                ('sentence', models.IntegerField(blank=True, default=0, verbose_name='Sentence In Years')),
                ('bail', models.IntegerField(blank=True, default=0, verbose_name='Bail Amount In Dollars')),
                ('charge', models.ManyToManyField(to='cases.charge')),
                ('defendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.defendant')),
                ('defendantGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.defendantgroup')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.judge')),
                ('judgeGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.judgegroup')),
            ],
        ),
    ]
