# Generated by Django 4.1.1 on 2022-11-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_region_defendant_region_defendantgroup_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defendant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='defendant',
            name='totalConvictions',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='totalCases',
        ),
        migrations.AddField(
            model_name='defendant',
            name='DIN',
            field=models.CharField(default='0000000', max_length=7, verbose_name='Departmental Identification Number'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='firstName',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Defendant First Name'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='lastName',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Defendant Last Name'),
        ),
        migrations.AddField(
            model_name='judge',
            name='firstName',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Judge First Name'),
        ),
        migrations.AddField(
            model_name='judge',
            name='lastName',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Judge Last Name'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='email',
            field=models.EmailField(blank=True, max_length=64, verbose_name='Defendant Email Address'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='region',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Defendant Region'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='email',
            field=models.EmailField(blank=True, max_length=64, verbose_name='Judge Email Address'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='region',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Judge Region'),
        ),
    ]
