# Generated by Django 4.1.1 on 2022-11-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_defendant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DIN', models.CharField(max_length=7, verbose_name='Departmental Identification Number')),
                ('firstName', models.CharField(max_length=32, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=32, verbose_name='Last Name')),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(max_length=1)),
                ('race', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='defendant',
            name='DIN',
        ),
        migrations.RemoveField(
            model_name='defendant',
            name='region',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='region',
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
