# Generated by Django 4.1.1 on 2022-11-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_convict_remove_defendant_din_remove_defendant_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendant',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Case Status'),
        ),
    ]
