# Generated by Django 4.1.1 on 2022-11-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_defendant_dob_judge_dob_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='classes',
            field=models.CharField(default='NA', max_length=64, verbose_name='Crime Class'),
            preserve_default=False,
        ),
    ]
