# Generated by Django 4.1.1 on 2022-11-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_charge_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendant',
            name='race',
            field=models.CharField(default='NA', max_length=260, verbose_name='Defendant Race'),
            preserve_default=False,
        ),
    ]
