# Generated by Django 4.1.1 on 2022-12-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_prison'),
    ]

    operations = [
        migrations.AddField(
            model_name='convict',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.prison'),
        ),
        migrations.AddField(
            model_name='convict',
            name='status',
            field=models.CharField(default='RELEASED', max_length=32),
            preserve_default=False,
        ),
    ]
