# Generated by Django 4.1.1 on 2022-12-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_convict_facility_convict_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='convict',
            name='charges',
            field=models.ManyToManyField(to='cases.charge'),
        ),
    ]
