# Generated by Django 4.1.1 on 2022-12-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_alter_convict_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convict',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.charge'),
        ),
    ]
