# Generated by Django 4.1.1 on 2022-12-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_convict_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convict',
            name='charge',
        ),
        migrations.AddField(
            model_name='convict',
            name='charge',
            field=models.ManyToManyField(to='cases.charge'),
        ),
    ]
