# Generated by Django 4.1.1 on 2022-12-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_remove_convict_charge_convict_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convict',
            name='charge',
            field=models.ManyToManyField(default=0, to='cases.charge'),
        ),
    ]
