# Generated by Django 4.1.1 on 2022-12-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_alter_defendant_middlename_alter_judge_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='convict',
            name='incarcerationEnd',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Imprisonment'),
        ),
        migrations.AddField(
            model_name='convict',
            name='sentenceEnd',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date'),
        ),
        migrations.AddField(
            model_name='convict',
            name='sentenceStart',
            field=models.DateField(blank=True, null=True, verbose_name='Date Sentencing Starts'),
        ),
    ]
