# Generated by Django 4.1.1 on 2022-12-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_convict_sentenceend_convict_sentencestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='convict',
            name='incarcerationEnd',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Imprisonment'),
        ),
    ]
