# Generated by Django 4.1.1 on 2022-12-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_convict_incarcerationend_convict_sentenceend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convict',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='race',
        ),
        migrations.AddField(
            model_name='convict',
            name='defendant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cases.defendant'),
            preserve_default=False,
        ),
    ]
