# Generated by Django 4.1.1 on 2022-12-02 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_convict_incarcerationend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convict',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='convict',
            name='race',
        ),
        migrations.AddField(
            model_name='convict',
            name='defendant',
            field=models.ForeignKey(default='UPDATE', on_delete=django.db.models.deletion.CASCADE, to='cases.defendant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convict',
            name='sentenceEnd',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date'),
        ),
    ]
