# Generated by Django 4.1.1 on 2022-12-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_remove_convict_age_remove_convict_dob_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Convict',
            new_name='Convictions',
        ),
        migrations.AlterField(
            model_name='defendant',
            name='middleName',
            field=models.CharField(default=' ', max_length=32, verbose_name='Middle Initial'),
        ),
    ]
