# Generated by Django 4.1.1 on 2022-12-02 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_remove_convict_age_remove_convict_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convict',
            name='defendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.defendant'),
        ),
    ]
