# Generated by Django 4.1.1 on 2022-12-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_alter_defendant_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='middleName',
            field=models.CharField(default=' ', max_length=32, verbose_name='Middle Initial'),
        ),
    ]
