# Generated by Django 4.1.1 on 2022-12-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_alter_defendant_middlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defendant',
            name='gender',
        ),
    ]
