# Generated by Django 4.1.1 on 2022-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_remove_defendant_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prison',
            old_name='city',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='case',
            name='region',
        ),
        migrations.RemoveField(
            model_name='defendantgroup',
            name='region',
        ),
        migrations.RemoveField(
            model_name='judgegroup',
            name='region',
        ),
        migrations.AddField(
            model_name='case',
            name='county',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Case County'),
        ),
        migrations.AddField(
            model_name='defendantgroup',
            name='county',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Defendant Group County'),
        ),
        migrations.AddField(
            model_name='judgegroup',
            name='county',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Judge Group County'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Defendant Age'),
        ),
    ]
