# Generated by Django 4.1.1 on 2022-12-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_rename_city_prison_county_remove_case_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prison',
            name='security',
            field=models.CharField(default='N.A', max_length=50, verbose_name='Maximum, Medium, Minimum'),
        ),
    ]
